### ISSUE TITLE
Kinetic Release

### ISSUE THREAD

**Issue by DLu** [ros-planning/navigation_msgs#1]
Needs a kinetic release. Currently on the blocking-other-packages list. Is there anything we want to change before we do so?

**Comment by wjwwood** [comment]
+1

**Comment by wjwwood** [comment]
I'll also mention that during the pre-beta period (now) you can release and then make changes after the initial release and release them later. The benefit is that we can get packages that depend on this (like rviz) released and fix them if/when you later make a change here.

**Comment by wjwwood** [comment]
This and `robot_model` are the only things blocking `rviz` now. Will anyone have time to look into this at the beginning of this week?

**Comment by mikeferguson** [comment]
I can release this tomorrow

**Comment by wjwwood** [comment]
Thanks @mikeferguson, I appreciate you taking the time to do it.

**Comment by mikeferguson** [comment]
For now I released 1.13.0 from jade-devel branch into kinetic (I see no need to fork the branch right now when there are no changes) https://github.com/ros/rosdistro/pull/11012

**Comment by wjwwood** [comment]
Thanks!
