### ISSUE TITLE
Release in Eloquent?

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation_msgs#11]

**Comment by jacobperron** [comment]
Yes, please!

I'm planning to release RViz and it is blocked by `map_msgs`.

**Comment by jacobperron** [comment]
@SteveMacenski Do you have power to do the release (and would you like to)?

**Comment by SteveMacenski** [comment]
I do not have the power. I wouldn't mind accumulating more power :wink:.

**Comment by wjwwood** [comment]
I believe the power has been granted for releases.

**Comment by jacobperron** [comment]
Looks like @mjcarroll beat us to it: https://github.com/ros/rosdistro/pull/22447

**Comment by mjcarroll** [comment]
I got the power.  I also released move_base_msgs into dashing (it previously wasn't).

**Comment by SteveMacenski** [comment]
Awesome. Well I have the power in the future. Glad its been resolved this round
