### ISSUE TITLE
Release navigation_msgs to Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros-planning/navigation_msgs#14]
Would you mind releasing `navigation_msgs` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 109 repos need it.

I'm not sure how much work it will need. At a minimum it needs #13.

**Comment by SteveMacenski** [comment]
I can take care of that tomorrow.

**Comment by mikeferguson** [comment]
I'm taking a look at this right now, because I feel like our branch names are wack right now.

**Comment by mikeferguson** [comment]
https://github.com/ros/rosdistro/pull/24034

**Comment by mikeferguson** [comment]
@sloretz - is there a cool webpage that tells us what is blocking what? I know it usually exists for each release, but I can never find it...

**Comment by sloretz** [comment]
@mikeferguson Yup, http://repositories.ros.org/status_page/blocked_releases_noetic.html

It gets regenerated every 6 hours.

**Comment by SteveMacenski** [comment]
@sloretz thanks for the link. There's a bunch on here I have control over. I'll be bloom'n on Friday.
