### ISSUE TITLE
Lunar release

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-planning/navigation_msgs#2]
Hi @mikeferguson and @DLu,
As you may know the next ROS release Lunar Loggerhead is around the corner :tada: 

Is it possible to release 1.13.0 into Lunar to allow [downstream packages](http://repositories.ros.org/status_page/blocked_releases_lunar.html?q=id%3D%22navigation_msgs%22&s=6&r=1) to be released?

Thanks!

**Comment by mikeferguson** [comment]
https://github.com/ros/rosdistro/pull/14543

**Comment by mikaelarguedas** [comment]
Thanks @mikeferguson !
