### ISSUE TITLE
ROS 2 build fails with (old) ament_tools

### ISSUE THREAD

**Issue by Martin-Idel-SI** [ros-planning/navigation_msgs#6]
The `package.xml` of `map_msgs` and `move_base_msgs` is lacking a build tool export

This means that `ament_tools` cannot build the package due to missing build type. 
Colcon seems to handle this correctly, so maybe this is not a problem moving forward.

**Comment by dirk-thomas** [comment]
@Martin-Idel-SI Thank you for reporting the problem. Please consider proposing a PR in the future when you already have a concrete proposal how to address the problem.

I created #7 to add the missing `build_type`.
