### ISSUE TITLE
move_base_msgs not included in melodic desktop_full

### ISSUE THREAD

**Issue by chrisl8** [ros-planning/navigation_msgs#9]
Sorry to throw this here, I am not sure if it is the right place, but I'm hoping.

When I run `rosinstall_generator desktop_full --rosdistro melodic --deps --tar > melodic-desktop-full.rosinstall` the resulting `.rosinstall` file includes `navigation_msgs/map_msgs`, but **NOT** `navigation_msgs/move_base_msgs`

This seems like an oversight, but I do not understand the system well enough to know were to report this or who to ask.

**Comment by mikeferguson** [comment]
We don't control the metapackages, so this isn't really actionable here.

I know the debians are generated from https://github.com/ros/metapackages -- but not sure if that's what rosinstall_generator uses.
